// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "fiber@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Endpoint untuk login user dan mengembalikan data user beserta token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login User",
                "parameters": [
                    {
                        "description": "Login User",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Succeed to POST data",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.LoginRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Endpoint untuk register user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register User",
                "parameters": [
                    {
                        "description": "Register User",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil login, mengembalikan data user",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Endpoint for get my profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get My Profile",
                "responses": {
                    "200": {
                        "description": "Succeed to get my profile",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Endpoint for get my profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update My Profile",
                "parameters": [
                    {
                        "description": "Update My Profile",
                        "name": "update-profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Succeed to update my profile",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/alamat": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Endpoint for get all my address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get My Alamat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Judul Alamat",
                        "name": "judul_alamat",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Succeed to get all my address",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.AlamatResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Endpoint for create new address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create My New Alamat",
                "parameters": [
                    {
                        "description": "Success to create new address",
                        "name": "update-profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InserAlamatReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Succeed to create new address",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/alamat/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Endpoint for get address by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get My Alamat By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the address",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Succeed to get address by id",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AlamatResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Endpoint for get address by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get My Alamat By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the address",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Success to update address",
                        "name": "update-alamat",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAlamatReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Succeed to update address by id",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AlamatResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Endpoint for delete address by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete My Alamat By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the address",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Succeed to update address by id",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/helper.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AlamatResp": {
            "description": "Data that will be returned in the response",
            "type": "object",
            "required": [
                "detail_alamat",
                "judul_alamat",
                "nama_penerima",
                "no_telp"
            ],
            "properties": {
                "detail_alamat": {
                    "type": "string",
                    "example": "Jl. Contoh No. 123"
                },
                "id": {
                    "type": "integer"
                },
                "judul_alamat": {
                    "type": "string",
                    "example": "Alamat Rumah"
                },
                "nama_penerima": {
                    "type": "string",
                    "example": "Budi"
                },
                "no_telp": {
                    "type": "string",
                    "example": "08123456789"
                }
            }
        },
        "dto.CityResp": {
            "description": "Data kota yang terkait dengan user",
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "1"
                },
                "name": {
                    "type": "string",
                    "example": "Bandung"
                },
                "province_id": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "dto.CreateUser": {
            "type": "object",
            "required": [
                "email",
                "id_kota",
                "id_provinsi",
                "jenis_kelamin",
                "kata_sandi",
                "name",
                "no_telp",
                "pekerjaan",
                "tanggal_lahir",
                "tentang"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "id_kota": {
                    "type": "string"
                },
                "id_provinsi": {
                    "type": "string"
                },
                "jenis_kelamin": {
                    "type": "string"
                },
                "kata_sandi": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "no_telp": {
                    "type": "string"
                },
                "pekerjaan": {
                    "type": "string"
                },
                "tanggal_lahir": {
                    "type": "string"
                },
                "tentang": {
                    "type": "string"
                }
            }
        },
        "dto.InserAlamatReq": {
            "description": "Data that will be used to insert a new address",
            "type": "object",
            "required": [
                "detail_alamat",
                "judul_alamat",
                "nama_penerima",
                "no_telp"
            ],
            "properties": {
                "detail_alamat": {
                    "type": "string",
                    "example": "Jl. Contoh No. 123"
                },
                "judul_alamat": {
                    "type": "string",
                    "example": "Alamat Rumah"
                },
                "nama_penerima": {
                    "type": "string",
                    "example": "Budi"
                },
                "no_telp": {
                    "type": "string",
                    "example": "08123456789"
                }
            }
        },
        "dto.Login": {
            "type": "object",
            "required": [
                "kata_sandi",
                "no_telp"
            ],
            "properties": {
                "kata_sandi": {
                    "type": "string"
                },
                "no_telp": {
                    "type": "string"
                }
            }
        },
        "dto.LoginRes": {
            "description": "Data yang dikembalikan setelah user berhasil login",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "L2DQK@example.com"
                },
                "id_kota": {
                    "$ref": "#/definitions/dto.CityResp"
                },
                "id_provinsi": {
                    "$ref": "#/definitions/dto.ProvinceResp"
                },
                "nama": {
                    "type": "string",
                    "example": "John Doe"
                },
                "no_telp": {
                    "type": "string",
                    "example": "1234567890"
                },
                "pekerjaan": {
                    "type": "string",
                    "example": "Software Engineer"
                },
                "tanggal_lahir": {
                    "type": "string",
                    "example": "1990-01-01"
                },
                "tentang": {
                    "type": "string",
                    "example": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "dto.ProvinceResp": {
            "description": "Data provinsi yang terkait dengan user",
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "1"
                },
                "name": {
                    "type": "string",
                    "example": "Jawa Barat"
                }
            }
        },
        "dto.UpdateAlamatReq": {
            "description": "Data that will be used to update an address",
            "type": "object",
            "required": [
                "detail_alamat",
                "nama_penerima",
                "no_telp"
            ],
            "properties": {
                "detail_alamat": {
                    "type": "string",
                    "example": "Jl. Contoh No. 123"
                },
                "nama_penerima": {
                    "type": "string",
                    "example": "Budi"
                },
                "no_telp": {
                    "type": "string",
                    "example": "08123456789"
                }
            }
        },
        "dto.UpdateUser": {
            "type": "object",
            "required": [
                "email",
                "id_kota",
                "id_provinsi",
                "jenis_kelamin",
                "nama",
                "no_telp",
                "pekerjaan",
                "tanggal_lahir",
                "tentang"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "id_kota": {
                    "type": "string"
                },
                "id_provinsi": {
                    "type": "string"
                },
                "jenis_kelamin": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "no_telp": {
                    "type": "string"
                },
                "pekerjaan": {
                    "type": "string"
                },
                "tanggal_lahir": {
                    "type": "string"
                },
                "tentang": {
                    "type": "string"
                }
            }
        },
        "dto.UserResp": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id_kota": {
                    "$ref": "#/definitions/dto.CityResp"
                },
                "id_provinsi": {
                    "$ref": "#/definitions/dto.ProvinceResp"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "nama": {
                    "type": "string"
                },
                "no_telp": {
                    "type": "string"
                },
                "pekerjaan": {
                    "type": "string"
                },
                "tanggal_lahir": {
                    "type": "string"
                },
                "tentang": {
                    "type": "string"
                }
            }
        },
        "helper.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {
                    "type": "array",
                    "items": {}
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "GoFiber Example API",
	Description:      "Golang GoFiber swagger auto generate step by step by swaggo",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
